version: "3.9"
services:
    frontend:
        build: .
        container_name: python-backend
        working_dir: /workspace
        volumes:
            - ./backend:/workspace
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - "127.0.0.1:8000:8000"
        restart: unless-stopped
        stdin_open: true
        tty: true
        command: ["bash", "/workspace/init.sh"]
volumes:
    backend: