services:
    frontend:
        build: .
        container_name: python-backend
        working_dir: /workspace
        volumes:
            - ./backend:/workspace
        ports:
            - "127.0.0.1:8000:8000"
        restart: unless-stopped
        stdin_open: true
        tty: true
        command: ["ash", "/workspace/init.sh"]